services:
  - type: web
    name: student-mental-health-predictor
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.app:app --bind 0.0.0.0:$PORT
